export const FIELD_LABELS: Record<string, string> = {
  quotationNo: "Quotation No.",
  quoteIssueDate: "Quote Issue Date",
  insuranceProduct: "Insurance Product",
  insurancePeriod: "Insurance Period",
  broker: "Broker",
  basicPremium: "Basic Premium (AED)",
  additionalCovers: "Additional Covers (AED)",
  taxRate: "Tax Rate (%)",
  insuredName: "Insured Name",
  mobileNo: "Mobile No.",
  dateOfBirth: "Date of Birth",
  emailId: "Email ID",
  ncdYears: "NCD (years)",
  tcfNo: "TCF No.",
  nationality: "Nationality",
  insuredType: "Insured Type",
  regLocPlate: "Reg loc, Plate Dtls",
  manufacturingYear: "Manufacturing Year",
  make: "Make",
  trimBodyType: "Trim / Body Type",
  cylinders: "No. Of. Cylinders",
  chassisNo: "Chassis No.",
  seatingCapacity: "Seating Capacity",
  gccSpecification: "GCC Specification",
  vehicleValue: "Vehicle Value (AED)",
  repairType: "Repair Type",
  hireCarCovered: "Hire Car for OD (7 Days)",
  hireCarPremium: "Hire Car Premium (AED)",
  agencyRepairCovered: "Agency Repair cover",
  basicDeductible: "Basic Deductible",
  lossOrDamage: "Loss or Damage",
  fireTheft: "Fire and Theft",
  thirdPartyBodily: "Third Party Bodily Injury",
  thirdPartyProperty: "Third Party Property Damage",
  pabDriver: "PAB for Driver",
  pabPassengers: "PAB for Passengers",
  pabFamily: "PAB for Family & Friends",
  geographicalArea: "Geographical Area Extension",
  stormFlood: "Storm, Flood, Riot & Strike",
  offRoad: "Off Road Cover",
  ambulance: "Ambulance Services",
  emergencyMedical: "Emergency Medical Exp.",
  windscreen: "Windscreen",
  personalEffects: "Personal Effects",
  roadsideAssistance: "Roadside Assistance",
};

export const STEP_META = [
  { id: "quotation", title: "Quotation & Premium", desc: "Quote header and premium summary." },
  { id: "insured", title: "Insured Details", desc: "Personal information of the insured." },
  { id: "vehicle", title: "Vehicle Details", desc: "Vehicle identification and valuation." },
  { id: "benefits", title: "Benefits Coverage", desc: "Choose covered benefits (default: Yes)." },
  { id: "covers", title: "Optional & Deductibles", desc: "Optional add-ons and deductible." },
] as const;
